[package]
name = "pjlink-bridge"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"

[[bin]]
name = "pjlink-rs232-bridge-runner"
path ="src/bin/bin.rs"
